sudo: false

language: node_js

node_js:
  - "0.12"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"

before_script:
  - npm install -g codecov

script:
  - npm run test
  - codecov

notifications:
  email:
    - vinta.chen@gmail.com
