language: node_js

node_js:
  - "0.10"

before_script:
  - gem install sass
  - npm install grunt-cli -g
  - npm install codecov.io -g

script:
  - grunt test

after_success:
  - codecov < ./coverage/lcov.info

notifications:
  email:
    - vinta.chen@gmail.com
