sudo: false

language: node_js

node_js:
  - "0.12"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"

script:
  - npm run test

after_script:
  - npm install -g codecov

after_success:
  - codecov < ./coverage/lcov.info

notifications:
  email:
    - vinta.chen@gmail.com
